version: "3.5"
services:
  grooming-app:
    build: .
    image: grooming-salon-app:latest
    container_name: grooming_app
    ports:
      - 8082:8082
    environment:
      DB_PASSWORD: postgres
      DB_URL: jdbc:postgresql://postgres:5432/salon_db
      DB_USERNAME: postgres
      EMAIL_PASSWORD: # Your app password
      EMAIL_USERNAME: # Your email password
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_database
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: salon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped



volumes:
  postgres_data: